### ISSUE TITLE
GameHandler: metod checkAnswer som kontrollerar rätt eller fel

### ISSUE THREAD

**Issue by viktorjonasson** [viktorjonasson/OOPJ-assignment-4-quizkampen#21]
Metoden anropas från Servern från det svar som skickats från ClientHandler (?)

För nu: i denna metod skriver vi vilket som är rätt svar, detta definieras som platsen i String-arrayen som är rätt.

Parameter till metoden är svaret, dvs strängen som sitter på knappen som spelaren klickade på.

Option 1 är rätt svar. I metoden behöver vi någon form av compare av sträng.

Return: boolean true/false.

**Comment by YlvaKodar** [comment]
Just nu är det inte platsen i stringarrayen som avgör, utan strängen som står på den valda svarsknappen.
